// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBPT-KCCBGsC0hj0EnkZDfKOEJudpn44QQ',
    appId: '1:609206827418:web:cf2f11d3be4dfc7ed5a223',
    messagingSenderId: '609206827418',
    projectId: 'number-slider',
    authDomain: 'number-slider.firebaseapp.com',
    storageBucket: 'number-slider.appspot.com',
    measurementId: 'G-GM424RKCLX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC81-mvpREMRzksbX6-avb1XL0bn87zz-w',
    appId: '1:609206827418:android:842c52997ec1e50dd5a223',
    messagingSenderId: '609206827418',
    projectId: 'number-slider',
    storageBucket: 'number-slider.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC-qbyDc5Au5UCXRmzK9y3Cw4246PUwsJ8',
    appId: '1:609206827418:ios:c32edcb26dd77153d5a223',
    messagingSenderId: '609206827418',
    projectId: 'number-slider',
    storageBucket: 'number-slider.appspot.com',
    iosClientId: '609206827418-1n9l7vuu6n1o0pj0r96e8ukn8oo1mvue.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterDemo',
  );
}
